### PR TITLE
Update comment

### PR DESCRIPTION
**Pull request by saxx**
Hi,

I added a simple request to update an existing comment - the one feature I couldn't find in your incredibly useful library.

I'm pretty sure I screwed up the architecture by adding a new Cards.UpdateComment next to Cards.AddComment (because that's under /actions/ endpoint, not under /cards/), but I couldn't find a better place. Also, I was missing an interface for comment actions, but I didn't want to change too much of your code.

Maybe you can use my few lines. Please let me know if I can do anything else to help or make my few lines fit better into your library. Thanks a lot for your work!

### CODE REVIEW

**Comment by dillenmeister** [comment]
Good addition, but I do have some comments :)

I try to follow the Trello API pretty closely and if they put this method under /actions/ I would like it to be under `Trello.Actions`. 

I actually think it should look something like this:

``` csharp
Trello.Actions.ChangeText(IActionId action, string text)
Trello.Actions.Delete(IActionId action) // Would be great if you could do this method too!
```

That resembles their API. Thing is that you can probably only use these methods for comment actions, but they made it look like you can use it for any action. I think it's better this way anyway.

(I've used the word _Change_ when dealing with one property and _Update_ when dealing with several properties at the same time, so `ChangeText` is more consistent with the rest of the code).

There is currently no interface called `IActionId`, but just have the `Action` class implement it (look at how `Card`, `List`, `Board` etc. does it).

Let me know what you think.

**Comment by saxx** [comment]
You're absolutely right, it's better to stick closely to their API.

I moved & renamed my UpdateComment(...) as you suggested, and added a Delete(...), both below Actions now.

Let me know what you think and if this works for you. Thanks again!

**Comment by dillenmeister** [comment]
This is looking really good!

Could you also add the methods to the IAsyncTrello interface? Like this:

``` csharp
Task ChangeText(IActionId action, string newText);
Task Delete(IActionId action)
```

There is also the automated test(s) left. Now, almost all tests in Trello.NET are integration tests using two Trello accounts where the username and password are not checked into the source control (the token is). If you want to do these tests, please email me at my github name at gmail.com and I will give the credentials to you. You don't necessarily need login to those accounts to create the tests, but it's often a bit easier to get it right then.

 If you don't want to do the tests, I will do them for this feature.

**Comment by saxx** [comment]
Thanks for your feedback. I added the async methods and the tests (I got them working without the credentials - ignore my e-mail ;).

Please let me know if I missed some test cases or if you have any further tips to improve my code.

**Comment by dillenmeister** [comment]
I like your tests!

There is a test in CardTests.cs called `Scenario_AddComment`. If you agree with me that the test is redundant now (because of `Scenario_AddAndUpdateComment`), please remove it.

Also, please rename the `ActionsUpdateRequest` class to `ActionsChangeTextRequest` (and the file name!).

Apart from that, I think this is a great pull request and will happily merge it in.

**Comment by saxx** [comment]
Thanks! I just pushed your suggestions.
Looking forward to seeing comment-updating in the NuGet package :)

**Pull request merged**
