### PR TITLE
Boards.AddMember, Boards.RemoveMember

### PR DESCRIPTION
**Pull request by andrewc89**
per issue #18
added listed methods
added async methods but I didn't test them as I have little experience with async
no tests written yet

### CODE REVIEW

**Comment by dillenmeister** [comment]
Looks great!

Two things:
- Will you do the test(s)? I think the email/fullname overload might be hard to test but add and then remove should be OK.
- Remove `this` if it's not needed (and I don't think it is anywhere).

I will pull this even if you don't do them, but I believe that it's the correct OSS etiquette to ask first. :)

**Comment by andrewc89** [comment]
Yeah I can do the tests. I might not get to them until tomorrow. I wasn't sure if you wanted the changes as one big pull request later on or one now and one later.

**Comment by dillenmeister** [comment]
I think it would be easiest to continue with this single pull request.

Ok, there's no hurry :) I asked because if I knew you were NOT doing the test then I would do it myself.

**Comment by andrewc89** [comment]
Alright I added two tests and fixed some parentheses formatting to match your code. I'm not sure how to test the `Boards.AddMember(board, email, fullName)` method. There are 17 tests failing which I think is the same number as before my fork but if not let me know.

**Comment by andrewc89** [comment]
Also none of the credentials you sent me seemed to work but, assuming I didn't break any of your other tests, it appears I didn't really need them.

**Comment by dillenmeister** [comment]
You actually broke the Search tests which is very strange I know. I changed the tests a little (https://github.com/dillenmeister/Trello.NET/commit/aeec0070fce2ee7fbab64e9c1ac5754d760db450?w=1). I combined the add and remove asserts in the same test because it's consistent with other tests. I too think that for a unit test there should be only one assert, but these are integration tests and they take a long time to run so I combine asserts where possible..

But a solid pull request, well done and thanks a lot!

**Comment by dillenmeister** [comment]
Upped new version to NuGet now with your changes!

**Pull request merged**
